trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: BuildAndTest
    displayName: Build and Test Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore solution'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--no-restore --configuration Release'

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        projects: 'tests/FCG.Tests/FCG.Tests.csproj'
        arguments: '--no-build --configuration Release'
        publishTestResults: true

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'XPlat'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'

    - task: DotNetCoreCLI@2
      displayName: 'Run BDD tests'
      inputs:
        command: 'test'
        projects: 'tests/FCG.Tests/FCG.BDD.Tests.csproj'
        arguments: '--no-build --configuration Release'
        publishTestResults: true

    - task: PublishCodeCoverageResults@2
      inputs:
        codeCoverageTool: 'XPlat'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'

    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: src/FCG.API/Dockerfile
        buildContext: $(Build.SourcesDirectory)/src
        tags: |
          $(REGISTRY_LOGIN_SERVER)/fcg.api:$(Build.BuildId)
