version: "3.9"

networks:
  fcg-rede:
    driver: bridge

services:
  fcg.api:
    image: fcg.api:latest
    build:
      context: .
      dockerfile: src/FCG.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - PORT=8080
    restart: unless-stopped
    networks:
      - fcg-rede
